name: Cppcheck

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  cppcheck:
    name: Run Cppcheck on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install Cppcheck
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y cppcheck
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install cppcheck
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          choco install cppcheck -y
        fi

    - name: List directory contents (debug)
      run: ls -R

    - name: Run Cppcheck
      run: |
        cppcheck --enable=all --inconclusive --std=c11 --force \
                 --suppress=missingIncludeSystem \
                 --inline-suppr \
                 -I Source/HKDS \
                 Source/HKDS 2> cppcheck-report.txt

    - name: Upload Cppcheck report
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-${{ matrix.os }}
        path: cppcheck-report.txt
